---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }} executable=pip3

- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: "{{ project_path }}/{{ main_app }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_syncdb is defined and run_django_sync_db
  tags: django.syncdb

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}/{{ main_app }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}/{{ main_app }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django.collectstatic

- name: Create superuser with default password
  django_manage:
    command: jmad_create_superuser {{ superuser_username }} {{ superuser_email }}
    app_path: "{{ project_path }}/{{ main_app }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: superuser_username is defined and superuser_email is defined
  tags: django.collectstatic
